### Sit Rep Columns
DATE_COLUMN = 'Date'
TIME_COLUMN = 'Time'
GLOBAL_CASES_COLUMN = 'Global Cases'
GLOBAL_DEATHS_COLUMN = 'Global Deaths'
US_CASES_COLUMN = 'US Cases'
US_DEATHS_COLUMN = 'US Deaths'

VA_CASES_TOTAL_COLUMN = 'VA Cases (Cumulative)'
VA_CASES_CHANGE_PREVIOUS_DAY_COLUMN = 'VA Cases Change Previous Day'
VA_POSITIVE_TEST_RATE_COLUMN = 'VA + Test Rate'
VA_POSITIVE_TEST_RATE_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'VA + Test Rate Change Since Previous Day'
VA_DEATHS_TOTAL_COLUMN = 'VA Deaths (Cumulative)'
VA_DEATHS_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'VA Deaths Change Since Previous Day'
VA_PRESENT_HOSPITALIZATIONS_CURRENT_COLUMN = 'VA Present Hospitalizations (Current)'
VA_PRESENT_HOSPITALIZATIONS_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'VA Current Hospitalizations Since Previous Day'
VA_PRESENT_HOSPITALIZATIONS_DISCHARGED_COLUMN = 'VA Hospitalizations Now Discharged'

DC_CASES_COLUMN = 'DC Cases'
DC_DEATHS_COLUMN = 'DC Deaths'
MD_CASES_COLUMN = 'MD Cases'
MD_DEATHS_COLUMN = 'MD Deaths'

FAIRFAX_CASES_COLUMN = ' Fairfax Cases (Cumulative)'
FAIRFAX_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'Fairfax Cases Change Since Previous Day'
FAIRFAX_POSITIVE_TEST_RATE_COLUMN = 'FCHD + Test Rate'
FAIRFAX_POSITIVE_TEST_RATE_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'FCHD + Rate Change Since Previous Day'
FAIRFAX_HOSPITALIZATIONS_COLUMN = 'Fairfax Hospitalizations'
FAIRFAX_DEATHS_COLUMN = 'Fairfax Deaths (Cumulative)'

ARLINGTON_CASES_COLUMN = 'Arlington Cases (Cumulative)'
ARLINGTON_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'Arlington Cases Change Since Previous Day'
ARLINGTON_POSITIVE_TEST_RATE_COLUMN = 'Arlington + Test Rate'
ARLINGTON_TEST_RATE_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'Arlington + Rate Change Since Previous Day'
ARLINGTON_HOSPITALIZATIONS_COLUMN = 'Arlington Hospitalizations'
ARLINGTON_DEATHS_COLUMN = 'Arlington Deaths (Cumulative)'

PW_CASES_COLUMN = 'PW Cases (Cumulative)'
PW_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'PW Cases Change Since Previous Day '
PW_POSITIVE_TEST_RATE_COLUMN = 'PW + Test Rate'
PW_POSITIVE_TEST_RATE_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'PW + Rate Change Since Previous Day'
PW_HOSPITALIZATIONS_COLUMN = 'PW Hospitalizations'
PW_DEATHS_COLUMN = 'PW Deaths (Cumulative)'

GMU_TOTAL_STUDENT_CASES_COLUMN = 'GMU Total Student Cases'
GMU_TOTAL_STUDENT_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'GMU Total Student Cases Change Since Previous Day'
GMU_RES_STUDENT_CASES_COLUMN = 'GMU Total Residential Student Cases'
GMU_RES_STUDENT_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'GMU Total Residential Student Cases Change Since Previous Day'
GMU_NON_RES_STUDENT_CASES_COLUMN = 'GMU Non-Residential Student Cases'
GMU_NON_RES_STUDENT_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'GMU Non-Residential Student Cases Change Since Previous Day'
GMU_EMPLOYEE_CASES_COLUMN = 'Employee Cases'
GMU_EMPLOYEE_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'Employee Cases Change Since Previous Day'
GMU_CONTRACTOR_CASES_COLUMN = 'Contractor Cases'
GMU_CONTRACTOR_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'Contractor Cases Change Since Previous Day'

ACTIVE_TOTAL_CASES_COLUMN = 'Active Cases (Total) (per OMMT Metrics)'
ACTIVE_TOTAL_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'Active Cases (Total) (per OMMT Metrics) Change Since Previous Day'
ACTIVE_RES_STUDENT_CASES_COLUMN = 'Active Cases (Residential) (per OMMT Metrics)'
ACTIVE_RES_STUDENT_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'Active Cases (Residential) (per OMMT Metrics) Change Since Previous Day'
ACTIVE_NON_RES_STUDENT_CASES_COLUMN = 'Active Cases (Non-Residential) (per OMMT Metrics)'
ACTIVE_NON_RES_STUDENT_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'Active Cases (Non-Residential) (per OMMT Metrics) Change Since Previous Day'
ACTIVE_EMPLOYEE_CASES_COLUMN = 'Active Cases (Employee) (per OMMT Metrics)'
ACTIVE_EMPLOYEE_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'Active Cases (Employee) (per OMMT Metrics) Change Since Previous Day'
ACTIVE_CONTRACTOR_CASES_COLUMN = 'Active Cases (Contractor) (per OMMT Metrics)'
ACTIVE_CONTRACTOR_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN = 'Active Cases (Contractor) (per OMMT Metrics) Change Since Previous Day'

column_title_to_letter_dicts = {
    DATE_COLUMN: 'A',
    TIME_COLUMN: 'B',
    GLOBAL_CASES_COLUMN: 'C',
    GLOBAL_DEATHS_COLUMN: 'D',
    US_CASES_COLUMN: 'E',
    US_DEATHS_COLUMN: 'F',

    VA_CASES_TOTAL_COLUMN: 'G',
    VA_CASES_CHANGE_PREVIOUS_DAY_COLUMN: 'H',
    VA_POSITIVE_TEST_RATE_COLUMN: 'I',
    VA_POSITIVE_TEST_RATE_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'J',
    VA_DEATHS_TOTAL_COLUMN: 'K',
    VA_DEATHS_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'L',
    VA_PRESENT_HOSPITALIZATIONS_CURRENT_COLUMN: 'M',
    VA_PRESENT_HOSPITALIZATIONS_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'N',
    VA_PRESENT_HOSPITALIZATIONS_DISCHARGED_COLUMN: 'O',

    # DC_CASES_COLUMN: 'P',
    # DC_DEATHS_COLUMN: 'Q',
    # MD_CASES_COLUMN: 'R',
    # MD_DEATHS_COLUMN: 'S',

    FAIRFAX_CASES_COLUMN: 'P',
    FAIRFAX_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'Q',
    FAIRFAX_POSITIVE_TEST_RATE_COLUMN: 'R',
    FAIRFAX_POSITIVE_TEST_RATE_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'S',
    # FAIRFAX_HOSPITALIZATIONS_COLUMN:
    # FAIRFAX_DEATHS_COLUMN:

    ARLINGTON_CASES_COLUMN: 'T',
    ARLINGTON_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'U',
    ARLINGTON_POSITIVE_TEST_RATE_COLUMN: 'V',
    ARLINGTON_TEST_RATE_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'W',
    # ARLINGTON_HOSPITALIZATIONS_COLUMN:
    # ARLINGTON_DEATHS_COLUMN:

    PW_CASES_COLUMN: 'X',
    PW_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'Y',
    PW_POSITIVE_TEST_RATE_COLUMN: 'Z',
    PW_POSITIVE_TEST_RATE_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'AA',
    # PW_HOSPITALIZATIONS_COLUMN: 'AF',
    # PW_DEATHS_COLUMN: 'AG'

    GMU_TOTAL_STUDENT_CASES_COLUMN: 'AB',
    GMU_TOTAL_STUDENT_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'AC',
    GMU_RES_STUDENT_CASES_COLUMN: 'AD',
    GMU_RES_STUDENT_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'AE',
    GMU_NON_RES_STUDENT_CASES_COLUMN: 'AF',
    GMU_NON_RES_STUDENT_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'AG',
    GMU_EMPLOYEE_CASES_COLUMN: 'AH',
    GMU_EMPLOYEE_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'AI',
    GMU_CONTRACTOR_CASES_COLUMN: 'AJ',
    GMU_CONTRACTOR_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'AK',

    ACTIVE_TOTAL_CASES_COLUMN: 'AL',
    ACTIVE_TOTAL_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'AM',
    ACTIVE_RES_STUDENT_CASES_COLUMN: 'AN',
    ACTIVE_RES_STUDENT_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'AO',
    ACTIVE_NON_RES_STUDENT_CASES_COLUMN: 'AP',
    ACTIVE_NON_RES_STUDENT_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'AQ',
    ACTIVE_EMPLOYEE_CASES_COLUMN: 'AR',
    ACTIVE_EMPLOYEE_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'AS',
    ACTIVE_CONTRACTOR_CASES_COLUMN: 'AT',
    ACTIVE_CONTRACTOR_CASES_CHANGE_SINCE_PREVIOUS_DAY_COLUMN: 'AU'
}

NO_DATA = 'no data'

NO_DATA_COLUMNS = [
    VA_PRESENT_HOSPITALIZATIONS_DISCHARGED_COLUMN,
    DC_CASES_COLUMN,
    DC_DEATHS_COLUMN,
    MD_CASES_COLUMN,
    MD_DEATHS_COLUMN
]