### Sit Rep Columns
DATE_COLUMN = 'Date'
TIME_COLUMN = 'Time'
GLOBAL_CASES_COLUMN = 'Global Cases'
GLOBAL_DEATHS_COLUMN = 'Global Deaths'
US_CASES_COLUMN = 'US Cases'
US_DEATHS_COLUMN = 'US Deaths'


VA_CASES_TOTAL_COLUMN = 'VA Cases (Total)'
VA_POSITIVE_TEST_RATE_COLUMN = 'VA + Test Rate'
VA_DEATHS_TOTAL_COLUMN = 'VA Deaths (Total)'

FAIRFAX_CASES_COLUMN = 'Fairfax Cases'
FAIRFAX_POSITIVE_TEST_RATE_COLUMN = 'FCHD + Test Rate'
FAIRFAX_HOSPITALIZATIONS_COLUMN = 'Fairfax Hospitalizations'
FAIRFAX_DEATHS_COLUMN = 'Fairfax Deaths'
ARLINGTON_CASES_COLUMN = 'Arlington Cases'
ARLINGTON_POSITIVE_TEST_RATE_COLUMN = 'Arlington + Test Rate'
ARLINGTON_HOSPITALIZATIONS_COLUMN = 'Arlington Hospitalizations'
ARLINGTON_DEATHS_COLUMN = 'Arlington Deaths'
PW_CASES_COLUMN = 'PW Cases'
PW_POSITIVE_TEST_RATE_COLUMN = 'PW Hospitalizations'
PW_HOSPITALIZATIONS_COLUMN = 'PW Hospitalizations'
PW_DEATHS_COLUMN = 'PW Deaths'

column_title_to_letter_dicts = {
    DATE_COLUMN: 'A',
    TIME_COLUMN: 'B',
    # GLOBAL_CASES_COLUMN: 'C',
    # GLOBAL_DEATHS_COLUMN: 'D',
    # US_CASES_COLUMN: 'E',
    # US_DEATHS_COLUMN: 'F',
    VA_CASES_TOTAL_COLUMN: 'G',
    VA_POSITIVE_TEST_RATE_COLUMN: 'H',
    VA_DEATHS_TOTAL_COLUMN: 'I',

    FAIRFAX_CASES_COLUMN: 'P',
    FAIRFAX_POSITIVE_TEST_RATE_COLUMN: 'Q',
    FAIRFAX_HOSPITALIZATIONS_COLUMN: 'R',
    FAIRFAX_DEATHS_COLUMN: 'S',
    ARLINGTON_CASES_COLUMN: 'T',
    ARLINGTON_POSITIVE_TEST_RATE_COLUMN: 'U',
    ARLINGTON_HOSPITALIZATIONS_COLUMN: 'V',
    ARLINGTON_DEATHS_COLUMN: 'W',
    PW_CASES_COLUMN: 'X',
    PW_POSITIVE_TEST_RATE_COLUMN: 'Y',
    PW_HOSPITALIZATIONS_COLUMN: 'Z',
    PW_DEATHS_COLUMN: 'AA'
}